In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('movies.csv')
display(df)

,title,year,rating,votes,runtime,certificate,genre,gross_total
0,The Shawshank Redemption,1994,9.3,"3,168,010",142,R,Drama,$29.33M
1,The Godfather,1972,9.2,"2,212,884",175,R,"Crime, Drama",$250.93M
2,The Dark Knight,2008,9.1,"3,145,646",152,PG-13,"Action, Crime, Drama",$1008.48M
3,The Godfather Part II,1974,9.0,"1,486,878",202,R,"Crime, Drama",$48.20M
4,12 Angry Men,1957,9.0,"977,359",96,Unrated,"Crime, Drama",$0.01M
...,...,...,...,...,...,...,...,...
245,Drishyam,2015,8.2,"107,875",163,Unrated,"Crime, Drama, Mystery",NaN
246,The Grapes of Wrath,1940,8.1,"108,041",129,Unrated,Drama,$0.01M
247,To Be or Not to Be,1942,8.1,"49,586",99,Unrated,"Comedy, Romance, War",$0.00M
248,Gangs of Wasseypur,2012,8.2,"113,517",321,Unrated,"Action, Comedy, Crime",$4.38M
249,Höstsonaten,1978,8.1,"41,972",99,PG,"Drama, Music",$0.04M

In [3]:
df.info()
df['gross_total'].isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        250 non-null    object
 1   year         250 non-null    int64
 2   rating       250 non-null    float64
 3   votes        250 non-null    object
 4   runtime      250 non-null    int64
 5   certificate  250 non-null    object
 6   genre        250 non-null    object
 7   gross_total  246 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 15.8+ KB

np.int64(4)

In [4]:
df = df.dropna(subset=['gross_total'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 246 entries, 0 to 249
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        246 non-null    object
 1   year         246 non-null    int64
 2   rating       246 non-null    float64
 3   votes        246 non-null    object
 4   runtime      246 non-null    int64
 5   certificate  246 non-null    object
 6   genre        246 non-null    object
 7   gross_total  246 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 17.3+ KB

In [5]:
df = df.rename(columns={'title': 'titulo', 'year': 'ano', 'rating': 'nota IMDB', 'votes': 'numero de votos','runtime': 'duração(min)', 'certificate': 'classificação indicativa', 'genre': 'genero','gross_total': 'bilheteria total(USD)'})
display(df)

,titulo,ano,nota IMDB,numero de votos,duração(min),classificação indicativa,genero,bilheteria total(USD)
0,The Shawshank Redemption,1994,9.3,"3,168,010",142,R,Drama,$29.33M
1,The Godfather,1972,9.2,"2,212,884",175,R,"Crime, Drama",$250.93M
2,The Dark Knight,2008,9.1,"3,145,646",152,PG-13,"Action, Crime, Drama",$1008.48M
3,The Godfather Part II,1974,9.0,"1,486,878",202,R,"Crime, Drama",$48.20M
4,12 Angry Men,1957,9.0,"977,359",96,Unrated,"Crime, Drama",$0.01M
...,...,...,...,...,...,...,...,...
244,Network,1976,8.1,"185,436",121,R,Drama,$23.70M
246,The Grapes of Wrath,1940,8.1,"108,041",129,Unrated,Drama,$0.01M
247,To Be or Not to Be,1942,8.1,"49,586",99,Unrated,"Comedy, Romance, War",$0.00M
248,Gangs of Wasseypur,2012,8.2,"113,517",321,Unrated,"Action, Comedy, Crime",$4.38M
249,Höstsonaten,1978,8.1,"41,972",99,PG,"Drama, Music",$0.04M

In [6]:
df['classificação indicativa'].value_counts()

classificação indicativa
R          102
Unrated     54
PG          37
PG-13       34
G           18
NC-17        1
Name: count, dtype: int64

In [7]:
mapa_classificacao = {
    'G': 'Livre',
    'PG': '10 anos',
    'PG-13': '13 anos',
    'R': '16 anos',
    'NC-17': '18 anos',
    'Unrated': 'Não classificado'
}
df['classificação indicativa'] = df['classificação indicativa'].map(mapa_classificacao)
display(df)

,titulo,ano,nota IMDB,numero de votos,duração(min),classificação indicativa,genero,bilheteria total(USD)
0,The Shawshank Redemption,1994,9.3,"3,168,010",142,16 anos,Drama,$29.33M
1,The Godfather,1972,9.2,"2,212,884",175,16 anos,"Crime, Drama",$250.93M
2,The Dark Knight,2008,9.1,"3,145,646",152,13 anos,"Action, Crime, Drama",$1008.48M
3,The Godfather Part II,1974,9.0,"1,486,878",202,16 anos,"Crime, Drama",$48.20M
4,12 Angry Men,1957,9.0,"977,359",96,Não classificado,"Crime, Drama",$0.01M
...,...,...,...,...,...,...,...,...
244,Network,1976,8.1,"185,436",121,16 anos,Drama,$23.70M
246,The Grapes of Wrath,1940,8.1,"108,041",129,Não classificado,Drama,$0.01M
247,To Be or Not to Be,1942,8.1,"49,586",99,Não classificado,"Comedy, Romance, War",$0.00M
248,Gangs of Wasseypur,2012,8.2,"113,517",321,Não classificado,"Action, Comedy, Crime",$4.38M
249,Höstsonaten,1978,8.1,"41,972",99,10 anos,"Drama, Music",$0.04M

In [8]:
def converter_bilheteria(valor):
    if pd.isna(valor):
        return None
    
    valor = valor.replace('$', '').strip()

    if 'M' in valor:
        return float(valor.replace('M', '')) * 1_000_000
    elif 'K' in valor:
        return float(valor.replace('$', '')) * 1_000
    else:
        return(valor)
    
df['bilheteria total(USD)'] = df['bilheteria total(USD)'].apply(converter_bilheteria)
df.info()
display(df)

<class 'pandas.core.frame.DataFrame'>
Index: 246 entries, 0 to 249
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   titulo                    246 non-null    object
 1   ano                       246 non-null    int64
 2   nota IMDB                 246 non-null    float64
 3   numero de votos           246 non-null    object
 4   duração(min)              246 non-null    int64
 5   classificação indicativa  246 non-null    object
 6   genero                    246 non-null    object
 7   bilheteria total(USD)     246 non-null    float64
dtypes: float64(2), int64(2), object(4)
memory usage: 17.3+ KB

,titulo,ano,nota IMDB,numero de votos,duração(min),classificação indicativa,genero,bilheteria total(USD)
0,The Shawshank Redemption,1994,9.3,"3,168,010",142,16 anos,Drama,2.933000e+07
1,The Godfather,1972,9.2,"2,212,884",175,16 anos,"Crime, Drama",2.509300e+08
2,The Dark Knight,2008,9.1,"3,145,646",152,13 anos,"Action, Crime, Drama",1.008480e+09
3,The Godfather Part II,1974,9.0,"1,486,878",202,16 anos,"Crime, Drama",4.820000e+07
4,12 Angry Men,1957,9.0,"977,359",96,Não classificado,"Crime, Drama",1.000000e+04
...,...,...,...,...,...,...,...,...
244,Network,1976,8.1,"185,436",121,16 anos,Drama,2.370000e+07
246,The Grapes of Wrath,1940,8.1,"108,041",129,Não classificado,Drama,1.000000e+04
247,To Be or Not to Be,1942,8.1,"49,586",99,Não classificado,"Comedy, Romance, War",0.000000e+00
248,Gangs of Wasseypur,2012,8.2,"113,517",321,Não classificado,"Action, Comedy, Crime",4.380000e+06
249,Höstsonaten,1978,8.1,"41,972",99,10 anos,"Drama, Music",4.000000e+04

In [9]:
df['numero de votos'] = df['numero de votos'].str.replace(',', '', regex=False).astype(int)

In [10]:
df.sort_values(by='bilheteria total(USD)', ascending=False).head(10)

,titulo,ano,nota IMDB,numero de votos,duração(min),classificação indicativa,genero,bilheteria total(USD)
73,Avengers: Endgame,2019,8.4,1432148,181,13 anos,"Action, Adventure, Sci-Fi",2.799440e+09
60,Avengers: Infinity War,2018,8.4,1359383,149,13 anos,"Action, Adventure, Sci-Fi",2.052420e+09
197,Spider-Man: No Way Home,2021,8.1,1007947,148,13 anos,"Action, Adventure, Fantasy",1.921430e+09
147,Top Gun: Maverick,2022,8.2,849682,130,13 anos,"Action, Drama",1.495700e+09
175,Harry Potter and the Deathly Hallows: Part 2,2011,8.1,1039009,130,13 anos,"Adventure, Family, Fantasy",1.342940e+09
5,The Lord of the Rings: The Return of the King,2003,9.0,2152126,201,13 anos,"Adventure, Drama, Fantasy",1.148970e+09
136,Jurassic Park,1993,8.2,1169814,127,13 anos,"Action, Adventure, Sci-Fi",1.103110e+09
74,The Dark Knight Rises,2012,8.4,1982116,164,13 anos,"Action, Crime, Drama",1.085430e+09
88,Joker,2019,8.3,1680640,122,16 anos,"Crime, Drama, Thriller",1.078960e+09
93,Toy Story 3,2010,8.3,964317,103,Livre,"Animation, Adventure, Comedy",1.067320e+09

In [11]:
df.to_csv('filmes.csv', index=False)